# Generated by Django 5.2.7 on 2026-02-11 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_group_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
